version: '2.1'
services:
  postgres:
    image: debezium/example-postgres:1.1
    platform: linux/amd64
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres





